
pipeline {
agent any

environment {
    PUBLIC_IP = "{{ public_ip }}"
}

stages {

    stage('Clone Kubernetes Repo') {
        steps {
            git branch: 'main', url: 'https://github.com/lavatech321/Kubernetes_CICD_Pipeline.git'
        }
    }

    stage('Update Deployment YAML') {
        steps {
            sh '''
            sed -i "s/REPLACE-IP/${PUBLIC_IP}/g" kubernetes-minikube-app-deploy/deployment/todo-app-deploy.yaml
            '''
        }
    }

    stage('Deploy to Minikube') {
        steps {
            sh '''
            kubectl apply -f kubernetes-minikube-app-deploy/deployment/todo-app-deploy.yaml
            '''
        }
    }

    stage('Wait for Deployment') {
        steps {
            sh 'sleep 60'
        }
    }

    stage('Verify Deployment') {
        steps {
            sh '''
            kubectl get pods
            kubectl get svc
            '''
        }
    }
}

}

