# tasks file for kubernetes
---

# ================= KUBECTL =================

- name: Download kubectl
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  args:
    chdir: /tmp

- name: Install kubectl
  copy:
    src: /tmp/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'
    remote_src: yes

# ================= MINIKUBE =================

- name: Download Minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /tmp/minikube

- name: Install Minikube
  copy:
    src: /tmp/minikube
    dest: /usr/local/bin/minikube
    mode: '0755'
    remote_src: yes

# ================= START CLUSTER =================

- name: Start Minikube
  command: minikube start --driver={{ minikube_driver }}
  register: minikube_output
  changed_when: "'Done!' in minikube_output.stdout"

